### ISSUE TITLE
ImportError: cannot import name 'PreTrainedBertModel'

### ISSUE THREAD

**Issue by rzhangpku** [lonePatient/bert-sentence-similarity-pytorch#1]
When I run `python train_bert_atec_nlp.py`, I get the error:

`Traceback (most recent call last):
  File "train_bert_atec_nlp.py", line 15, in <module>
    from pybert.model.nn.bert_fine import BertFine
  File "~/bert-sentence-similarity-pytorch/pybert/model/nn/bert_fine.py", line 3, in <module>
    from pytorch_pretrained_bert.modeling import PreTrainedBertModel, BertModel`
`ImportError: cannot import name 'PreTrainedBertModel'`

Thank you very much!

**Comment by rzhangpku** [comment]
Replace 'PreTrainedBertModel' with 'BertPreTrainedModel', and it is solved.
